### PR TITLE
Restart to fetch dataset name list when connection is lost

### LINKED ISSUE #269: Restart fetching dataset name list in realtime part when the connection is lost
### Feature you want to implement
In realtime part of dataviewer app, when the websocket connection is lost, one should be able to restart fetching dataset name list.

### How the feature is implemented
This will be implemented similarly to #250.

### PR DESCRIPTION
**Pull request by BECATRUE**
This closes #269.

When the connection is lost, the "restart" button is enabled.

### CODE REVIEW

**Comment by kangz12345** [comment]
Please resolve the conflicts!

**Comment by BECATRUE** [comment]
I knew there was going to be a conflict while implementing this😂

**Comment by BECATRUE** [comment]
A Pylint warning occurs because there are similar codes checking if the websocket connection is valid.

Maybe we are going to implement a base class for `QThread` connecting to ARTIQ-PROXY later, so is it okay to disable this warning temporarily?

**Comment by kangz12345** [comment]
> A Pylint warning occurs because there are similar codes checking if the websocket connection is valid.
> 
> Maybe we are going to implement a base class for `QThread` connecting to ARTIQ-PROXY later, so is it okay to disable this warning temporarily?

Okay, then please create an issue about this and disable the warning for now.

**Comment by BECATRUE** [comment]
To solve the `duplicate-code` Pylint warning, the forced-push could not be avoided. Please understand.

**Review by kangz12345 — APPROVED** [review]
LGTM

**Pull request merged**
