### PR TITLE
Fix various bugs when fetching dataset name list

### LINKED ISSUE #293: Dataset viewer has some problem with remote mode
### Describe the bug
In realtime mode, new dataset didn't appear, so I toggled to remote mode but still a new RID didn't appear.
When I switched back to the realtime mode, now there were several datasets but something was strange (sorry for ambiguity).
Few moments later I found the following error messages (repeated several times):
```shell
Traceback (most recent call last):
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1328, in startRemoteListThread
    self.remoteListThread.quit()
RuntimeError: wrapped C/C++ object of type _RemoteListThread has been deleted
```

### To Reproduce
IDK yet.

### PR DESCRIPTION
**Pull request by BECATRUE**
This resolves #293.

As I checked, it seems that all bugs were resolved.
However, please check it in your environment, too.

### CODE REVIEW

**Comment by kangz12345** [comment]
Many bugs are fixed, but the fast change of hour combobox is still buggy.
I got the following error:
```shell
Traceback (most recent call last):
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1229, in _handleDatasetClicked
    self.startRemoteDatasetThread(name)
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1355, in startRemoteDatasetThread
    self.remoteDatasetThread.quit()
RuntimeError: wrapped C/C++ object of type _RemoteDatasetThread has been deleted
```
After this error occurs, every combobox change (including RID combobox) prints the same error.

**Comment by BECATRUE** [comment]
Maybe, that problem is resolved now.

Please check it again. @kangz12345

**Comment by kangz12345** [comment]
Indeed it resolved the problem!

**Review by kangz12345 — APPROVED** [review]
LGTM!

**Pull request merged**
