### PR TITLE
Add `logger` back

### LINKED ISSUE #100: Revert a wrong commit
See also: https://github.com/snu-quiqcl/iquip/commit/85a6eb5821d67d0f7ed491eee43b5123c933e072#commitcomment-123892867

### PR DESCRIPTION
**Pull request by giwon2004**
This reverts a wrong commit made by me while reverting "merge commit to the branch" back mentioned in [`85a6eb5`#commitcomment-123892867](https://github.com/snu-quiqcl/iquip/commit/85a6eb5821d67d0f7ed491eee43b5123c933e072#commitcomment-123892867)

This closes #100.

### CODE REVIEW

**Comment by BECATRUE** [comment]
As @kangz12345 and I realized, it is not only `setup.json`, but also logging parts in all apps.

Could you check this, again? @giwon2004

**Comment by kangz12345** [comment]
Can you actually revert that commit (using the git feature)?

**Comment by kangz12345** [comment]
If it makes conflicts with other PR, e.g., #99, we can resolve it.

**Comment by giwon2004** [comment]
I will try it soon.

**Review by kangz12345 — APPROVED** [review]
👍

**Review by BECATRUE — APPROVED** [review]
LGTM!

**Pull request merged**
