### PR TITLE
Use `requirements.txt` instead of direct installation

### LINKED ISSUE #286: Use `requirements.txt` instead of direct installation
### Feature you want to implement
To manage easily, we need to use a requirements file instead of direct installation in GitHub actions.

### PR DESCRIPTION
**Pull request by BECATRUE**
This closes #286.

After merged, I will release the first official version, v1.0.0.

### CODE REVIEW

**Review by kangz12345 — COMMENTED** [review]
I think even if `numpy` is included in other packages, we should include it in the `requirements.txt` because the package dependencies might change.
We are using `numpy` so it should be explicitly required to be installed.

**Comment by BECATRUE** [comment]
I see! I will add its dependency.

**Comment by BECATRUE** [comment]
I realized at least the last two-year `numpy` versions support since 3.9.
Sure, it is easy to install different `numpy` version according to the Python version.
However, the support for Python 3.8 will end sometime this year, so why not check about this version in GitHub actions?

**Comment by kangz12345** [comment]
> I realized at least the last two-year `numpy` versions support since 3.9. Sure, it is easy to install different `numpy` version according to the Python version. However, the support for Python 3.8 will end sometime this year, so why not check about this version in GitHub actions?

That makes sense. I agree with you.

**Review by kangz12345 — APPROVED** [review]

**Pull request merged**
