### PR TITLE
Fix a bug when changing the remote mode rapidly

### LINKED ISSUE #277: Error when changing time or rid rapidly (dataviewer remote)
### Describe the bug
When I change the hour or rid very fast (using mouse wheel), iquip crashes or printing the error below:
```shell
Traceback (most recent call last):
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1224, in _handleDatasetClicked
    self.startRemoteDatasetThread(name)
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1340, in startRemoteDatasetThread
    rid = int(self.remotePart.ridComboBox.currentText())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

### Expected behavior
The program should be stable even if the hour or rid is changed rapidly.

### To Reproduce
1. Open iquip with dataviewer.
2. Scroll the mouse wheel on the rid combobox.
3. The program exits.

### PR DESCRIPTION
**Pull request by BECATRUE**
This resolved #277.

As I tested, there is a slight delay when scrolling rapidly.
However, it seems to be allowed and moderately efficient.

### CODE REVIEW

**Comment by kangz12345** [comment]
This solution has a problem, right?

**Comment by BECATRUE** [comment]
Didn't this PR resolve the problem? Did you mean it has another problem? @kangz12345

**Comment by kangz12345** [comment]
Oh so this is the final solution, okay I misunderstood.

**Review by kangz12345 — APPROVED** [review]
I didn't check the delay but maybe it will not be a big problem. Let's fix it later if it is!

**Comment by BECATRUE** [comment]
This problem may bother you a little bit, but at least it doesn't kill the GUI, so let's fix it later.

**Pull request merged**
